/** Hub Actions */
export const CREATE_HUB_SUCCESS = "CREATE_HUB_SUCCESS";
export const DELETE_HUB_SUCCESS = "DELETE_HUB_SUCCESS";
export const GET_HUB_SUCCESS = "GET_HUB_SUCCESS";
export const SEARCH_HUBS_SUCCESS = "SEARCH_HUBS_SUCCESS";
export const UPDATE_HUB_SUCCESS = "UPDATE_HUB_SUCCESS";

/** Schedule Actions */
export const CREATE_SCHEDULE_SUCCESS = "CREATE_SCHEDULE_SUCCESS";
export const DELETE_SCHEDULE_SUCCESS = "DELETE_SCHEDULE_SUCCESS";
export const GET_SCHEDULE_SUCCESS = "GET_SCHEDULE_SUCCESS";
export const SEARCH_SCHEDULES_SUCCESS = "SEARCH_SCHEDULES_SUCCESS";
export const UPDATE_SCHEDULE_SUCCESS = "UPDATE_SCHEDULE_SUCCESS";

/** Schedule Event Actions */
export const CREATE_SCHEDULE_EVENT_SUCCESS = "CREATE_SCHEDULE_EVENT_SUCCESS";
export const DELETE_SCHEDULE_EVENT_SUCCESS = "DELETE_SCHEDULE_EVENT_SUCCESS";
export const GET_SCHEDULE_EVENT_SUCCESS = "GET_SCHEDULE_EVENT_SUCCESS";
export const SEARCH_SCHEDULE_EVENTS_SUCCESS = "SEARCH_SCHEDULE_EVENTS_SUCCESS";
export const UPDATE_SCHEDULE_EVENT_SUCCESS = "UPDATE_SCHEDULE_EVENT_SUCCESS";

/* Socket Middleware Action */
export const ESTABLISH_SOCKET_CONNECTION = "ESTABLISH_SOCKET_CONNECTION";
export const SOCKET_CONNECTED = "SOCKET_CONNECTED";
export const SOCKET_DISCONNECTED = "SOCKET_DISCONNECTED";
export const SOCKET_SEND_MESSAGE = "SOCKET_SEND_MESSAGE";

/** Toggle Stuff */
export const TOGGLE_NOTIFICATION_SUCCESS = "TOGGLE_NOTIFICATION_SUCCESS";
